name: appwrite_dart_function
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '^2.17.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  dart_appwrite: 8.0.0
  lints: ^2.0.0

